stages:
  - test
  - deploy


unit-test-job:
  stage: test
  image: node:latest
  services:
    - name: postgres:latest
      alias: postgres
  variables:
    POSTGRES_DB: mydatabase
    POSTGRES_USER: root
    POSTGRES_PASSWORD: 1
    PG_DB_URL: postgres://root:1@postgres:5432/mydatabase
  script:
    - echo "Installing dependencies..."
    - npm install
    - echo "Create Database..."
    - echo "Creating .env file..."
    - echo "SECRET_KEY=MyNewSecretKey123!@#" > .env
    - echo "PG_DB_URL=postgres://root:1@postgres:5432/mydatabase" >> .env
    - echo "Running unit tests..."
    - npm run test:unit
    - echo "Code coverage is 90%"

deploy-job:
  stage: deploy
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
