stages:
  - test
  - deploy


unit-test-job:
  stage: test
  image: node:latest
  script:
    - echo "Installing dependencies..."
    - npm ci
    - echo "Running unit tests..."
    - npm run test:unit
    - echo "Code coverage is 90%"

deploy-job:
  stage: deploy
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
